//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class areagriddetail
    {
        public int id { get; set; }
        public int areagridid { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string areaname { get; set; }
        public int areatype { get; set; }
        public int gridx { get; set; }
        public int gridy { get; set; }
        public string gridx_y { get; set; }
    }
}
