//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class autojoblog
    {
        public string id { get; set; }
        public int type { get; set; }
        public string message { get; set; }
        public System.DateTimeOffset recordtime { get; set; }
        public int executetype { get; set; }
        public long executeduration { get; set; }
    }
}
