//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basestationlog
    {
        public int id { get; set; }
        public string tableid { get; set; }
        public Nullable<int> detailid { get; set; }
        public string beforetxt { get; set; }
        public string aftertxt { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> taskid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string tasktype { get; set; }
        public string changecontext { get; set; }
    }
}
