//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicelicensing
    {
        public int id { get; set; }
        public string esn { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string androidversion { get; set; }
        public string skversion { get; set; }
        public Nullable<bool> issupportvolte { get; set; }
        public Nullable<bool> issupportvoice { get; set; }
        public Nullable<int> state { get; set; }
        public string authorizingname { get; set; }
        public Nullable<int> lastupdateuserid { get; set; }
        public string lastupdateusername { get; set; }
        public Nullable<System.DateTime> expirytime { get; set; }
        public string deviceid { get; set; }
        public string companyname { get; set; }
        public Nullable<int> companyid { get; set; }
        public string privatekey { get; set; }
        public string devicetag { get; set; }
    }
}
