//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicelocation
    {
        public int id { get; set; }
        public string deviceid { get; set; }
        public Nullable<double> altitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> accuracy { get; set; }
        public Nullable<long> loctiontimestamp { get; set; }
        public Nullable<long> apptimestamp { get; set; }
        public int imsitaskid { get; set; }
        public int gridx { get; set; }
        public int gridy { get; set; }
        public System.DateTimeOffset loctiontimestamptz { get; set; }
        public int istesting { get; set; }
    }
}
