//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceunattended
    {
        public int id { get; set; }
        public string deviceid { get; set; }
        public Nullable<int> imsitaskid { get; set; }
        public Nullable<int> taskstopstate { get; set; }
        public Nullable<int> batterylevel { get; set; }
        public Nullable<long> totalspace { get; set; }
        public Nullable<long> availablespace { get; set; }
        public Nullable<int> rat { get; set; }
        public Nullable<int> logswitch { get; set; }
        public Nullable<int> testswitch { get; set; }
        public Nullable<int> pcapswitch { get; set; }
        public string alias { get; set; }
        public string registrationid { get; set; }
        public Nullable<double> altitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> accuracy { get; set; }
        public Nullable<long> statetimestamp { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<long> lastonlinetime { get; set; }
    }
}
