//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicedatasubmeterstate
    {
        public string id { get; set; }
        public string tablename { get; set; }
        public int tabletype { get; set; }
        public int state { get; set; }
        public System.DateTimeOffset datastarttime { get; set; }
        public System.DateTimeOffset dataendtime { get; set; }
        public System.DateTimeOffset tablecreatetime { get; set; }
        public Nullable<System.DateTimeOffset> stateupdatetime { get; set; }
        public int effective { get; set; }
        public int datasection { get; set; }
    }
}
