//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtconfig
    {
        public int id { get; set; }
        public Nullable<int> taskunitid { get; set; }
        public Nullable<int> gridcovratio { get; set; }
        public Nullable<int> gridsize { get; set; }
        public Nullable<int> szsp { get; set; }
        public string zs { get; set; }
        public string pd { get; set; }
        public Nullable<int> taskunitdevicegroupid { get; set; }
        public Nullable<int> totalsample { get; set; }
        public Nullable<int> rsrp { get; set; }
        public Nullable<int> sinr { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> locationinterval { get; set; }
        public string locationmode { get; set; }
    }
}
