//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileinfooverview
    {
        public int id { get; set; }
        public Nullable<long> startuploadtime { get; set; }
        public Nullable<long> enduploadtime { get; set; }
        public Nullable<long> dataduration { get; set; }
        public Nullable<int> uploadsize { get; set; }
        public Nullable<int> uploadcount { get; set; }
        public Nullable<int> totalcount { get; set; }
        public Nullable<int> taskid { get; set; }
        public string deviceid { get; set; }
    }
}
