//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileinfo
    {
        public int id { get; set; }
        public Nullable<int> taskid { get; set; }
        public Nullable<int> taskunitid { get; set; }
        public Nullable<int> uploadtype { get; set; }
        public Nullable<int> filetype { get; set; }
        public string filename { get; set; }
        public Nullable<int> filebatch { get; set; }
        public Nullable<long> filesize { get; set; }
    }
}
