//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imsitask
    {
        public int id { get; set; }
        public Nullable<int> taskid { get; set; }
        public string imsi { get; set; }
        public string jsontext { get; set; }
        public Nullable<int> isrevise { get; set; }
        public string imei { get; set; }
        public string iname { get; set; }
        public string isdn { get; set; }
        public Nullable<bool> islock { get; set; }
        public Nullable<int> relationdeviceid { get; set; }
        public Nullable<bool> modifiable { get; set; }
        public Nullable<bool> completed { get; set; }
        public Nullable<bool> confirmed { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public Nullable<System.DateTime> modifiedat { get; set; }
        public Nullable<System.DateTime> completedat { get; set; }
        public Nullable<System.DateTime> confirmedat { get; set; }
        public Nullable<int> taskstatus { get; set; }
        public Nullable<long> createdatl { get; set; }
        public Nullable<long> modifiedatl { get; set; }
        public Nullable<long> completedatl { get; set; }
        public Nullable<long> confirmedatl { get; set; }
        public string taskreport { get; set; }
        public Nullable<int> createuserid { get; set; }
        public string createusername { get; set; }
        public Nullable<int> reviseuserid { get; set; }
        public string reviseusername { get; set; }
        public Nullable<long> updatedat { get; set; }
        public Nullable<long> claimedat { get; set; }
        public string taskname { get; set; }
        public Nullable<int> taskunitdevicegroupid { get; set; }
        public Nullable<int> deviceid { get; set; }
        public Nullable<int> fileupstate { get; set; }
    }
}
