//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indexmapgatherhistory
    {
        public string id { get; set; }
        public int companyid { get; set; }
        public string carrier { get; set; }
        public string mobilemode { get; set; }
        public string areaid { get; set; }
        public int areatype { get; set; }
        public int type { get; set; }
        public decimal data { get; set; }
        public decimal data2 { get; set; }
        public decimal data3 { get; set; }
        public decimal data4 { get; set; }
        public decimal data5 { get; set; }
        public System.DateTimeOffset statisticstime { get; set; }
        public System.DateTimeOffset datatime { get; set; }
    }
}
