//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indoorlayerdetail
    {
        public int id { get; set; }
        public Nullable<int> layerid { get; set; }
        public string picturename { get; set; }
        public string fullname { get; set; }
        public string pictureurl { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<long> createdate { get; set; }
        public Nullable<int> picturewidth { get; set; }
        public Nullable<int> pictureheight { get; set; }
        public Nullable<int> maprotation { get; set; }
        public string serverpath { get; set; }
        public Nullable<int> elevator { get; set; }
    }
}
