//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localtask
    {
        public string id { get; set; }
        public string taskid { get; set; }
        public string taskname { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<long> createtime { get; set; }
        public string createusername { get; set; }
        public Nullable<long> modifytime { get; set; }
        public Nullable<int> modifyuserid { get; set; }
        public string modifyusername { get; set; }
        public string deviceid { get; set; }
        public Nullable<int> ftpserver { get; set; }
        public string remotepath { get; set; }
    }
}
