//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database : DbContext
    {
        public Database()
            : base("name=Database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminrolesort> adminrolesort { get; set; }
        public virtual DbSet<adminuser> adminuser { get; set; }
        public virtual DbSet<adminuserareas> adminuserareas { get; set; }
        public virtual DbSet<adminuserdistribution> adminuserdistribution { get; set; }
        public virtual DbSet<adminusergroup> adminusergroup { get; set; }
        public virtual DbSet<adminuserrole> adminuserrole { get; set; }
        public virtual DbSet<appexceptioninfo> appexceptioninfo { get; set; }
        public virtual DbSet<areagrid> areagrid { get; set; }
        public virtual DbSet<areagriddetail> areagriddetail { get; set; }
        public virtual DbSet<areas> areas { get; set; }
        public virtual DbSet<authorityinfo> authorityinfo { get; set; }
        public virtual DbSet<authorizebasestation> authorizebasestation { get; set; }
        public virtual DbSet<authorizedevice> authorizedevice { get; set; }
        public virtual DbSet<authorizelayer> authorizelayer { get; set; }
        public virtual DbSet<authorizeproject> authorizeproject { get; set; }
        public virtual DbSet<authorizereporttemplate> authorizereporttemplate { get; set; }
        public virtual DbSet<authorizeroutemanage> authorizeroutemanage { get; set; }
        public virtual DbSet<authorizetasktemplate> authorizetasktemplate { get; set; }
        public virtual DbSet<authorizetesttemplate> authorizetesttemplate { get; set; }
        public virtual DbSet<autojoblog> autojoblog { get; set; }
        public virtual DbSet<basestation> basestation { get; set; }
        public virtual DbSet<basestationlog> basestationlog { get; set; }
        public virtual DbSet<command> command { get; set; }
        public virtual DbSet<companyinfo> companyinfo { get; set; }
        public virtual DbSet<countrysingle> countrysingle { get; set; }
        public virtual DbSet<countrysinglehistory> countrysinglehistory { get; set; }
        public virtual DbSet<countrysinglemonth> countrysinglemonth { get; set; }
        public virtual DbSet<countrysingletesttime> countrysingletesttime { get; set; }
        public virtual DbSet<cqtconfig> cqtconfig { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<device> device { get; set; }
        public virtual DbSet<devicedatasubmeter> devicedatasubmeter { get; set; }
        public virtual DbSet<devicedatasubmeterstate> devicedatasubmeterstate { get; set; }
        public virtual DbSet<devicefrequency> devicefrequency { get; set; }
        public virtual DbSet<devicelicensing> devicelicensing { get; set; }
        public virtual DbSet<devicelocation> devicelocation { get; set; }
        public virtual DbSet<devicescreenshot> devicescreenshot { get; set; }
        public virtual DbSet<deviceunattended> deviceunattended { get; set; }
        public virtual DbSet<dictionarycollection> dictionarycollection { get; set; }
        public virtual DbSet<dtconfig> dtconfig { get; set; }
        public virtual DbSet<exceptioninfo> exceptioninfo { get; set; }
        public virtual DbSet<executeprogress> executeprogress { get; set; }
        public virtual DbSet<executionstatus> executionstatus { get; set; }
        public virtual DbSet<fileinfo> fileinfo { get; set; }
        public virtual DbSet<fileinfodetail> fileinfodetail { get; set; }
        public virtual DbSet<fileinfooverview> fileinfooverview { get; set; }
        public virtual DbSet<ftpmanager> ftpmanager { get; set; }
        public virtual DbSet<functioninfo> functioninfo { get; set; }
        public virtual DbSet<functionmapper> functionmapper { get; set; }
        public virtual DbSet<gisinfo> gisinfo { get; set; }
        public virtual DbSet<gisinfodetail> gisinfodetail { get; set; }
        public virtual DbSet<imsis> imsis { get; set; }
        public virtual DbSet<imsitask> imsitask { get; set; }
        public virtual DbSet<indexmapgather> indexmapgather { get; set; }
        public virtual DbSet<indexmapgatherhistory> indexmapgatherhistory { get; set; }
        public virtual DbSet<indexnorm> indexnorm { get; set; }
        public virtual DbSet<indextop> indextop { get; set; }
        public virtual DbSet<indextophistory> indextophistory { get; set; }
        public virtual DbSet<indoorconfig> indoorconfig { get; set; }
        public virtual DbSet<indoorlayer> indoorlayer { get; set; }
        public virtual DbSet<indoorlayerdetail> indoorlayerdetail { get; set; }
        public virtual DbSet<localtask> localtask { get; set; }
        public virtual DbSet<logfilenamerule> logfilenamerule { get; set; }
        public virtual DbSet<marketsingle> marketsingle { get; set; }
        public virtual DbSet<marketsinglehistory> marketsinglehistory { get; set; }
        public virtual DbSet<marketsinglemonth> marketsinglemonth { get; set; }
        public virtual DbSet<marketsingletesttime> marketsingletesttime { get; set; }
        public virtual DbSet<menuinfo> menuinfo { get; set; }
        public virtual DbSet<multitaskreportitem> multitaskreportitem { get; set; }
        public virtual DbSet<multitaskreportmapper> multitaskreportmapper { get; set; }
        public virtual DbSet<multitaskstreamengineeringparam> multitaskstreamengineeringparam { get; set; }
        public virtual DbSet<multitaskstreamfilelist> multitaskstreamfilelist { get; set; }
        public virtual DbSet<multitaskstreaminfo> multitaskstreaminfo { get; set; }
        public virtual DbSet<projectareamapping> projectareamapping { get; set; }
        public virtual DbSet<projectgismapping> projectgismapping { get; set; }
        public virtual DbSet<projectimagemapping> projectimagemapping { get; set; }
        public virtual DbSet<projectinfo> projectinfo { get; set; }
        public virtual DbSet<projectroutemapping> projectroutemapping { get; set; }
        public virtual DbSet<projectsitemapping> projectsitemapping { get; set; }
        public virtual DbSet<projectusermapping> projectusermapping { get; set; }
        public virtual DbSet<provincialsingle> provincialsingle { get; set; }
        public virtual DbSet<provincialsinglehistory> provincialsinglehistory { get; set; }
        public virtual DbSet<provincialsinglemonth> provincialsinglemonth { get; set; }
        public virtual DbSet<provincialsingletesttime> provincialsingletesttime { get; set; }
        public virtual DbSet<railwayconfig> railwayconfig { get; set; }
        public virtual DbSet<reportitem> reportitem { get; set; }
        public virtual DbSet<reportmapper> reportmapper { get; set; }
        public virtual DbSet<roleinfo> roleinfo { get; set; }
        public virtual DbSet<routedetailinfo> routedetailinfo { get; set; }
        public virtual DbSet<routeinfo> routeinfo { get; set; }
        public virtual DbSet<routemanage> routemanage { get; set; }
        public virtual DbSet<routemanagedetail> routemanagedetail { get; set; }
        public virtual DbSet<skylog> skylog { get; set; }
        public virtual DbSet<streaminfo> streaminfo { get; set; }
        public virtual DbSet<subtask> subtask { get; set; }
        public virtual DbSet<subtaskroutemapping> subtaskroutemapping { get; set; }
        public virtual DbSet<sysdictdetail> sysdictdetail { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<taskannex> taskannex { get; set; }
        public virtual DbSet<taskfileclear> taskfileclear { get; set; }
        public virtual DbSet<taskgroup> taskgroup { get; set; }
        public virtual DbSet<taskgroupwithtaskmap> taskgroupwithtaskmap { get; set; }
        public virtual DbSet<tasklogfilenamerule> tasklogfilenamerule { get; set; }
        public virtual DbSet<tasklogfilenamerulemap> tasklogfilenamerulemap { get; set; }
        public virtual DbSet<taskmonitor> taskmonitor { get; set; }
        public virtual DbSet<taskmonitoritem> taskmonitoritem { get; set; }
        public virtual DbSet<taskplan> taskplan { get; set; }
        public virtual DbSet<taskplanlog> taskplanlog { get; set; }
        public virtual DbSet<taskplanstate> taskplanstate { get; set; }
        public virtual DbSet<taskplanwithtaskmap> taskplanwithtaskmap { get; set; }
        public virtual DbSet<taskreport> taskreport { get; set; }
        public virtual DbSet<tasktemplate> tasktemplate { get; set; }
        public virtual DbSet<taskunattended> taskunattended { get; set; }
        public virtual DbSet<taskunit> taskunit { get; set; }
        public virtual DbSet<taskunitdevicegroup> taskunitdevicegroup { get; set; }
        public virtual DbSet<taskunitdevicegroupmapping> taskunitdevicegroupmapping { get; set; }
        public virtual DbSet<templatelist> templatelist { get; set; }
        public virtual DbSet<templateresourcemanage> templateresourcemanage { get; set; }
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<testcarmanage> testcarmanage { get; set; }
        public virtual DbSet<testdevicelocationinfo> testdevicelocationinfo { get; set; }
        public virtual DbSet<testdevicelocationinfonoavail> testdevicelocationinfonoavail { get; set; }
        public virtual DbSet<testdurationinfo> testdurationinfo { get; set; }
        public virtual DbSet<testkilometreinfo> testkilometreinfo { get; set; }
        public virtual DbSet<testkpiinfo> testkpiinfo { get; set; }
        public virtual DbSet<testtemplate> testtemplate { get; set; }
        public virtual DbSet<validationconfig> validationconfig { get; set; }
        public virtual DbSet<versionmanage> versionmanage { get; set; }
        public virtual DbSet<devicekpi> devicekpi { get; set; }
        public virtual DbSet<devicestate> devicestate { get; set; }
        public virtual DbSet<indexresource> indexresource { get; set; }
        public virtual DbSet<jpushlog> jpushlog { get; set; }
        public virtual DbSet<readyreport> readyreport { get; set; }
        public virtual DbSet<routeformapinfo> routeformapinfo { get; set; }
        public virtual DbSet<streamengineeringparam> streamengineeringparam { get; set; }
        public virtual DbSet<streamfilelist> streamfilelist { get; set; }
    }
}
