//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectinfo
    {
        public int id { get; set; }
        public Nullable<int> projectid { get; set; }
        public string projectname { get; set; }
        public string manager { get; set; }
        public string testuserids { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> status { get; set; }
        public string progress { get; set; }
        public Nullable<int> devicevender { get; set; }
        public Nullable<int> carrier { get; set; }
        public Nullable<int> outsourcers { get; set; }
        public string area { get; set; }
        public Nullable<int> ftpserver { get; set; }
        public string tasktype { get; set; }
        public Nullable<int> taskltemplate { get; set; }
        public Nullable<int> sites { get; set; }
        public string taskparameter { get; set; }
        public Nullable<int> createuserid { get; set; }
        public string createusername { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> lastupdateuserid { get; set; }
        public string lastupdateusername { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public Nullable<int> reporttemplate { get; set; }
        public Nullable<long> starttimel { get; set; }
        public Nullable<long> endtimel { get; set; }
        public Nullable<long> createtimel { get; set; }
        public Nullable<long> lastupdatetimel { get; set; }
        public string remotepath { get; set; }
        public string carriername { get; set; }
        public string devicevendername { get; set; }
        public string outsourcersname { get; set; }
        public string ftpservername { get; set; }
        public string taskltemplatename { get; set; }
        public string sitesname { get; set; }
        public string testusername { get; set; }
        public string managername { get; set; }
        public string sitestableid { get; set; }
        public string areaname { get; set; }
        public string taskparametername { get; set; }
        public string tasktypename { get; set; }
        public Nullable<bool> byfrequency { get; set; }
    }
}
