//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleinfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string remarks { get; set; }
        public System.DateTime createtime { get; set; }
        public int createuserid { get; set; }
        public string createusername { get; set; }
        public int companyid { get; set; }
    }
}
