//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class routeformapinfo
    {
        public int id { get; set; }
        public int routeid { get; set; }
        public string routetable { get; set; }
        public int mapinfotype { get; set; }
        public string coordinate { get; set; }
    }
}
