//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class routedetailinfo
    {
        public int id { get; set; }
        public Nullable<int> routeid { get; set; }
        public string stationname { get; set; }
        public Nullable<float> altitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<int> startstationno { get; set; }
        public Nullable<int> endstationno { get; set; }
        public string kpis { get; set; }
    }
}
