//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class routeinfo
    {
        public int id { get; set; }
        public string routename { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<int> createuserid { get; set; }
        public string description { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string linename { get; set; }
        public string linecolor { get; set; }
        public string area { get; set; }
        public Nullable<int> ismapinfo { get; set; }
    }
}
