//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtask
    {
        public int id { get; set; }
        public Nullable<int> imsitaskid { get; set; }
        public string type { get; set; }
        public string standard { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> testcount { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createusername { get; set; }
        public string finishusername { get; set; }
        public Nullable<System.DateTime> revisetime { get; set; }
        public string reviseusername { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<int> reviseuserid { get; set; }
        public Nullable<long> starttimel { get; set; }
        public Nullable<long> endtimel { get; set; }
        public Nullable<long> finishtimel { get; set; }
        public Nullable<long> createtimel { get; set; }
        public Nullable<long> revisetimel { get; set; }
        public Nullable<int> taskstatus { get; set; }
        public Nullable<int> no { get; set; }
        public Nullable<long> updatedat { get; set; }
        public string taskunitname { get; set; }
        public Nullable<int> fileupstate { get; set; }
        public Nullable<int> filebatch { get; set; }
        public string finishtime { get; set; }
        public Nullable<int> taskunitid { get; set; }
    }
}
