//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskplan
    {
        public int id { get; set; }
        public string planname { get; set; }
        public Nullable<int> repeattype { get; set; }
        public Nullable<long> starttimel { get; set; }
        public Nullable<long> endtimel { get; set; }
        public Nullable<long> intervaltime { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string errormessage { get; set; }
        public Nullable<System.DateTime> lastexecute { get; set; }
        public Nullable<int> executecount { get; set; }
    }
}
