//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskunattended
    {
        public int id { get; set; }
        public int taskid { get; set; }
        public int type { get; set; }
        public long intervaltime { get; set; }
        public int intervaltype { get; set; }
        public Nullable<System.DateTimeOffset> theoryexecutetime { get; set; }
        public Nullable<System.DateTimeOffset> realityexecutetime { get; set; }
        public Nullable<System.DateTimeOffset> nextexecutetime { get; set; }
        public int createuserid { get; set; }
        public string createusername { get; set; }
        public System.DateTimeOffset createtime { get; set; }
        public string taskname { get; set; }
        public Nullable<int> projectid { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<int> imsitaskid { get; set; }
        public string iname { get; set; }
        public string imei { get; set; }
    }
}
