//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskplanlog
    {
        public int id { get; set; }
        public long executetimel { get; set; }
        public string executeresult { get; set; }
        public string errormessage { get; set; }
        public int taskid { get; set; }
        public int taskplanid { get; set; }
        public Nullable<int> status { get; set; }
    }
}
