//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskfileclear
    {
        public int id { get; set; }
        public Nullable<int> taskid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> cleartime { get; set; }
        public Nullable<int> issuccess { get; set; }
        public string exceptionmessage { get; set; }
        public Nullable<int> ftpid { get; set; }
        public string ip { get; set; }
        public string path { get; set; }
    }
}
