//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasklogfilenamerulemap
    {
        public int id { get; set; }
        public Nullable<int> projectid { get; set; }
        public Nullable<int> taskid { get; set; }
        public string nameparts { get; set; }
        public Nullable<int> dateindex { get; set; }
        public Nullable<int> timeindex { get; set; }
        public Nullable<int> siteidindex { get; set; }
        public Nullable<int> cellidindex { get; set; }
        public Nullable<int> pciindex { get; set; }
        public Nullable<int> floorinfoindex { get; set; }
        public Nullable<int> elevatorinfoindex { get; set; }
        public Nullable<int> commandinfoindex { get; set; }
        public Nullable<int> imeiindex { get; set; }
        public string connectsymbol { get; set; }
        public string province { get; set; }
        public Nullable<int> provinceindex { get; set; }
        public string city { get; set; }
        public Nullable<int> cityindex { get; set; }
        public string area { get; set; }
        public Nullable<int> areaindex { get; set; }
        public string address { get; set; }
        public Nullable<int> addressindex { get; set; }
        public string description { get; set; }
        public Nullable<int> descriptionindex { get; set; }
        public string sitename { get; set; }
        public Nullable<int> sitenameindex { get; set; }
    }
}
