//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int id { get; set; }
        public Nullable<int> projectid { get; set; }
        public Nullable<int> tasktype { get; set; }
        public string taskname { get; set; }
        public string taskusername { get; set; }
        public Nullable<int> taskstatus { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string filestatus { get; set; }
        public string filesize { get; set; }
        public string reports { get; set; }
        public Nullable<int> taskuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createusername { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> revisetime { get; set; }
        public string reviseusername { get; set; }
        public Nullable<int> reviseuserid { get; set; }
        public Nullable<int> imsicount { get; set; }
        public Nullable<int> sites { get; set; }
        public Nullable<int> taskltemplate { get; set; }
        public Nullable<int> reporttemplate { get; set; }
        public Nullable<long> starttimel { get; set; }
        public Nullable<long> endtimel { get; set; }
        public Nullable<long> createtimel { get; set; }
        public Nullable<long> revisetimel { get; set; }
        public Nullable<bool> confirmed { get; set; }
        public Nullable<long> updatedat { get; set; }
        public Nullable<int> fileupstate { get; set; }
        public Nullable<int> reportstate { get; set; }
        public Nullable<int> checkstate { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTimeOffset> checktime { get; set; }
        public Nullable<int> wayofcreation { get; set; }
        public Nullable<int> extragxtid { get; set; }
        public Nullable<bool> createdatedir { get; set; }
        public Nullable<int> amounttype { get; set; }
        public Nullable<int> taskplanid { get; set; }
        public Nullable<int> downsitetype { get; set; }
    }
}
