//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskunit
    {
        public int id { get; set; }
        public Nullable<int> tasktemplateid { get; set; }
        public Nullable<int> taskunitdevicegroupid { get; set; }
        public string tasktype { get; set; }
        public Nullable<int> testtemplateid { get; set; }
        public string cammandtemplate { get; set; }
        public string repeatcontrol { get; set; }
        public string logcode { get; set; }
        public string pcap { get; set; }
        public Nullable<int> testtimes { get; set; }
        public Nullable<int> timeinterval { get; set; }
        public string mark { get; set; }
    }
}
