//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPgsqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasktemplate
    {
        public int id { get; set; }
        public string templatename { get; set; }
        public string reporttype { get; set; }
        public string telrgent { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public int reportitemid { get; set; }
        public Nullable<bool> isabled { get; set; }
        public string tasktype { get; set; }
    }
}
